season: null

paths:
  raw_dir: data/raw
  processed_dir: data/processed
  match_overrides_csv: data/manual/player_match_overrides.csv

projection:
  systems: [batx, steamer, oopsy, atc]
  system_weights:
    batx: 3
    steamer: 2
    oopsy: 3
    atc: 1
  category_weights:
    pa: 2.3
    hr: 1.35
    sb: 1.0
    r: 0.6
    rbi: 0.6
    h: 1.0
  pa_floor: 200
  starter_rank_metric: z_total_custom
  league:
    num_teams: 15
    hitter_slots:
      c: 2
      b1: 1
      b2: 1
      b3: 1
      ss: 1
      of: 5
      ci: 1
      mi: 1
      ut: 1
  auction:
    total_budget: 260
    hitter_budget_share: 0.70
    min_bid: 1

pitcher:
  projection:
    system: oopsy
  google_sheets:
    workbook_url: "https://docs.google.com/spreadsheets/d/1fZoopAlDnyibFkDgw8fa0R02GJlZqsESufsxg-i34ck/edit?usp=sharing"
    integrated_tab: "Pitcher Integrated"
    sp_skillz_tab: "Pitcher SP Skillz"
    auto_export: true
  sp_skillz:
    source_url: "https://www.fangraphs.com/leaders/major-league?pos=all&stats=pit&lg=all&type=c%2C7%2C8%2C14%2C13%2C55%2C57%2C-1%2C6%2C62%2C122%2C42%2C-1%2C120%2C331%2C121%2C29%2C31%2C-1%2C105%2C110%2C-1%2C386%2C387%2C388&month=0&ind=0&team=0&rost=0&age=0&filter&players=0&startdate&enddate&v_cr=legacy&qual=5&season1=2025&season=2025"
    lookback_season: 2025
    num_teams: 15
    sp_depth: 10
    start_share_min: 0.67
    use_ip_paradigms: true
    low_ip_max_start_ip: 80
    high_ip_min_start_ip: 100
    gs_fallback_threshold: 5
    weights:
      tbf: 0
      ip_per_gs: 0
      siera: -1
      xfip: -1
      k_minus_bb_pct: 1
      contact_pct: -1
      csw_pct: 1
      ball_pct: -1
      stuff_plus: 1.5
      pitching_plus: 2
    low_ip_weights:
      tbf: 0
      ip_per_gs: 0
      siera: -0.76
      xfip: -0.42
      k_minus_bb_pct: 1.23
      contact_pct: -2.0
      csw_pct: 1.26
      ball_pct: -0.01
      stuff_plus: 1.75
      pitching_plus: 1.15
    high_ip_weights:
      tbf: 0
      ip_per_gs: 0
      siera: -1.61
      xfip: -1.34
      k_minus_bb_pct: 2.0
      contact_pct: -1.73
      csw_pct: 1.19
      ball_pct: -0.58
      stuff_plus: 1.56
      pitching_plus: 1.64
    stabilization_points:
      tbf: 1
      ip_per_gs: 1
      siera: 30
      xfip: 30
      k_minus_bb_pct: 120
      contact_pct: 150
      csw_pct: 200
      ball_pct: 150
      stuff_plus: 100
      pitching_plus: 300
    reliability_method: "sample_over_sample_plus_stab"
    eno:
      sheet_url: "https://docs.google.com/spreadsheets/d/1daR9RNic3GcfDb6FLsm2OZRBS8VkqucOqHSnIS7ru5c/edit?usp=sharing"
      sheet_tab: "Feb 3 Ranks"
      include_2026_stuff_plus: true

adp:
  local_tsv: data/raw/ADP.tsv
  draft_type: 897
  num_teams: 12
  lookback_days: 14
  fill_missing_with_max: true

google_sheets:
  workbook_url: "https://docs.google.com/spreadsheets/d/1jq1-54WLaKh6ADZjEYB9VC1vLPNU4h2p7TH68A0TXMk/edit?usp=sharing"
  source_ranks_url: "https://docs.google.com/spreadsheets/d/1xjwmHUT_AvZB0UMPRMPUlnW-waFpfWPWcNdKBA4k7us/edit?usp=sharing"
  run_data_tab: Run Data
  projection_tab: Projections_Bats
  adp_tab: ADP
  rbll_tab: RBLL Team & Targets

quality:
  min_rows_per_system: 500
  min_zscore_rows: 150
  min_weighted_rows: 300
  min_adp_match_rate: 0.35
  fail_on_adp_match_rate: false
